### ISSUE TITLE
Pydantic 2.0+ import issue

### ISSUE THREAD

**Issue by xaviernogueira** [mansenfranzen/autodoc_pydantic#161]
Hi all. Thanks for the great package. I was migrating a library to pydantic 2.0 and realized our docs don't build anymore due to the following change on Pydantics side.

**The core issue is that "`BaseSettings` has been moved to the `pydantic-settings` package."** See the full traceback below.

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xpublish/envs/215/lib/python3.11/site-packages/sphinx/registry.py", line 459, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/.asdf/installs/python/3.11.4/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/xpublish/envs/215/lib/python3.11/site-packages/sphinxcontrib/autodoc_pydantic/__init__.py", line 11, in <module>
    from sphinxcontrib.autodoc_pydantic.directives.autodocumenters import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/xpublish/envs/215/lib/python3.11/site-packages/sphinxcontrib/autodoc_pydantic/directives/autodocumenters.py", line 10, in <module>
    from pydantic import BaseSettings, BaseModel
  File "/home/docs/checkouts/readthedocs.org/user_builds/xpublish/envs/215/lib/python3.11/site-packages/pydantic/__init__.py", line 207, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/xpublish/envs/215/lib/python3.11/site-packages/pydantic/_migration.py", line 288, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0.3/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.0.3/u/import-error
```

**This should be a quick import fix?** I was originally thinking about pulling down the repo and making a pull request, but it appears the tests are already failing, and you use a dev environment (tox) I am not quite used to. Happy to do so if others are busy, but this could be more efficiently done by someone else?

Thanks

**Comment by mansenfranzen** [comment]
Hi @xaviernogueira,

your issue is related to #146 and is actively worked on in #160. 

Unfortunately, is not simple as swapping the import :-(. It is way more sophisticated because pydantic v2 changed semantics and public/internal API. 

For the meanwhile, stay tuned.
