### ISSUE TITLE
When using `pydantic.v1`'s `BaseModel`: AttributeError: type object '[BaseModel instance]' has no attribute '__pydantic_decorators__'`

### ISSUE THREAD

**Issue by jlnav** [mansenfranzen/autodoc_pydantic#302]
Hello!

Is the following just simply an issue of autodoc_pydantic not supporting `pydantic.v1` (https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features) ?

Given a very simple `BaseModel`:

```python

from pydantic.v1 import BaseModel

class AllocSpecs(BaseModel):
    """
    Specifications for configuring an Allocation Function.
    """

    user: Optional[dict] = {"num_active_gens": 1}
    """
    A user-data dictionary to place bounds, constants, settings, or other parameters
    for customizing the allocation function.
    """

    outputs: list = Field([], alias="out")
    """
    List of 2- or 3-tuples corresponding to NumPy dtypes. e.g. ``("dim", int, (3,))``, or ``("path", str)``.
    """
```

(without any validators)

Attempting to document it in a `.rst` file:

```rst
.. autopydantic_model:: libensemble.specs.AllocSpecs
  :model-show-json: False
  :model-show-config-member: False
  :model-show-config-summary: False
  :model-show-validator-members: False
  :model-show-validator-summary: False
  :model-hide-reused-validator: True
```

I receive the following:

```python
$ cat /var/folders/t0/1ksqgw4d091bgkczj89jb1tm0000gq/T/sphinx-err-0s_s4dfc.log
# Platform:         darwin; (macOS-14.5-arm64-arm-64bit)
# Sphinx version:   8.0.2
# Python version:   3.11.8 (CPython)
# Docutils version: 0.21.2
# Jinja2 version:   3.1.4
# Pygments version: 2.18.0

# Last messages:
#   bibliography
#   
#   
#   reading sources... [  4%]
#   contributing
#   
#   
#   reading sources... [  5%]
#   data_structures/alloc_specs
#   

# Loaded extensions:
#   sphinx.ext.mathjax (8.0.2)
#   alabaster (1.0.0)
#   sphinxcontrib.applehelp (2.0.0)
#   sphinxcontrib.devhelp (2.0.0)
#   sphinxcontrib.htmlhelp (2.1.0)
#   sphinxcontrib.serializinghtml (2.0.0)
#   sphinxcontrib.qthelp (2.0.0)
#   sphinxcontrib.spelling (8.0.0)
#   sphinxcontrib.bibtex (2.6.2)
#   sphinx.ext.autodoc.preserve_defaults (8.0.2)
#   sphinx.ext.autodoc.type_comment (8.0.2)
#   sphinx.ext.autodoc.typehints (8.0.2)
#   sphinx.ext.autodoc (8.0.2)
#   sphinx.ext.napoleon (8.0.2)
#   sphinx.ext.intersphinx (8.0.2)
#   sphinx.ext.imgconverter (8.0.2)
#   sphinxcontrib.autodoc_pydantic (2.2.0)
#   sphinx_design (0.5.0)
#   sphinx_copybutton (0.5.2)
#   sphinxcontrib.jquery (4.1)
#   sphinx_rtd_theme (unknown version)

# Traceback:
Traceback (most recent call last):
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/application.py", line 378, in build
    self.builder.build_update()
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 317, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 424, in read
    self._read_serial(docnames)
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 476, in _read_serial
    self.read_doc(docname)
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 535, in read_doc
    publisher.publish()
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/io.py", line 106, in read
    self.parse()
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/parsers.py", line 83, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2790, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
                   ^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2369, in explicit_construct
    return method(self, expmatch)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2106, in directive
    return self.run_directive(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2156, in run_directive
    result = directive_instance.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/ext/autodoc/directive.py", line 139, in run
    documenter.generate(more_content=self.content)
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/ext/autodoc/__init__.py", line 1872, in generate
    return super().generate(more_content=more_content,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinx/ext/autodoc/__init__.py", line 940, in generate
    self.add_content(more_content)
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinxcontrib/autodoc_pydantic/directives/autodocumenters.py", line 290, in add_content
    self.add_field_summary()
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinxcontrib/autodoc_pydantic/directives/autodocumenters.py", line 512, in add_field_summary
    if not self.pydantic.inspect.fields:
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinxcontrib/autodoc_pydantic/directives/autodocumenters.py", line 121, in inspect
    self._inspect = ModelInspector(obj)
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinxcontrib/autodoc_pydantic/inspection.py", line 455, in __init__
    self.field_validator_mappings = self.get_field_validator_mapping()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnavarro/miniconda3/envs/libe/lib/python3.11/site-packages/sphinxcontrib/autodoc_pydantic/inspection.py", line 473, in get_field_validator_mapping
    decorators = self.model.__pydantic_decorators__
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'AllocSpecs' has no attribute '__pydantic_decorators__'
```

Please let me know if you need more information. Thank you very much!

**Comment by mansenfranzen** [comment]
Hi @jlnav,

thanks for raising the issue here!

Unlike `pydantic`, `autodoc_pydantic` does not support legacy pydantic v1 in autodoc_pydantic v2. 

In June 2023, pydantic v2 was released. This introduced backwards incompatible API and behavioral changes in comparison to pydantic v1. Hence, autodoc_pydantic required substantial adjustments, too. In order to keep the codebase clean and concise, separate versions for v1 and v2 were created.

If you want to document pydantic v1 models, please use autodoc_pydantic 1.x instead of 2.x.

I hope this clarification helps. Feel free to reopen.

**Comment by mansenfranzen** [comment]
@allcontributors please add @jlnav for question
